site_name: The GOMA pipeline 
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.footer
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  - Running the GOMA pipeline: index.md
  - GOMA vAlpha 1.0: workflow_alpha.md
  - GOMA vBeta 0.1: workflow_beta.md
  - Software used: reference.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/linkedin
      link: https://linkedin.com/in/gian-schüpbach-330351310

copyright: Copyright &copy; 2025 Gian Schüpbach
